### ISSUE TITLE
Error/Warning at startup

### ISSUE THREAD

**Issue by ragnar76** [freemint/qed#6]
Hi there,

QED runs fine without NVDI but when i start it with mint/xaaes but without NVDI enabled i get this error:

"pid ${randomnumber}" (QED): XaAES: Print dialogs unavailable with current VDI"

It's very annoying. Do you think it is possible to move the alertbox into the printerdialog (or just right after klicking "print" or pressing the keyboard shortcut)?

bye
Bernd

**Comment by mikrosk** [comment]
You are right, it is very annoying. :) I was fine with it because so far, using NVDI/fVDI is part of recommended freemint setup. But I think we could just print it to the console.

**Comment by mikrosk** [comment]
@th-otto claims this has been fixed yesterday but I don't see it anywhere in history?

**Comment by th-otto** [comment]
On Dienstag, 9. Juni 2020 08:42:11 CEST Miro Kropáček wrote:
> I don't see it anywhere in history?

Hmpf. Pushed the XaAES changed, but not qed. Done now.

**Comment by mikrosk** [comment]
I guess we can close this one as well.

**Comment by ragnar76** [comment]
yes, can be closed
