### ISSUE TITLE
Title of Untitled window is cleared upon iconification

### ISSUE THREAD

**Issue by xdelatour** [freemint/qed#7]
When the user iconifies an untitled window, the title is cleared.

Steps to reproduce:
- Run qed
- Go to `File` / `New text` to open a new 'Untitled' window
- Click on the Iconify button
- The iconified window has no title
- Double-click on the iconified window, the title bar of the full window is empty

IMHO, the bug is inside the CF-Lib. 
1.  qed calls wi_iconify()
2. wi_iconify() calls make_shortpath()  
3. make_shortpath() calls [split_filename()](https://github.com/freemint/cflib/blob/master/fssplitf.c#L31)

If there is neither '/' nor '\\' in the full filename, split_filename() returns an empty string

Fix (not tested):
I guess adding `else { if (name != NULL) strcpy(name, fullname); }`  after `if (str!=NULL) {...}` will be enough to fix the bug

**Comment by mikrosk** [comment]
Nice find. I was considering fixing it in Qed (as there's a chance someone depends on this `split_filename` behaviour) but Toswin, Qed and CF-Lib seemed OK (always passing full paths there) so I went ahead and added it to CF-Lib.
